import Head from "next/head";
import styled from "@emotion/styled";
import Link from "next/link";
import HomeJoinUs from "../components/HomeJoinUs";
import HomeSectors from "../components/HomeSectors";
import HomeAbout from "../components/HomeAbout";

const HomeGlobal = styled.div`
  background-color: rgb(10, 20, 100);
`;

export default function Home() {
  return (
    <HomeGlobal>
      <Head>
        <title>District Money - Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <HomeJoinUs />
      <HomeSectors />
      <HomeAbout />
    </HomeGlobal>
  );
}
