import Head from "next/head";
import React from "react";
import Simulation from "../components/Simulation";
import styled from "@emotion/styled";

const InvestmentGlobal = styled.div`
  background-color: rgb(10, 20, 100);
`;

function investment() {
  return (
    <InvestmentGlobal>
      <Head>
        <title>District Money - Investissement</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Simulation />
    </InvestmentGlobal>
  );
}

export default investment;
