import Head from "next/head";
import React from "react";
import LexiqueList from "../components/Lexique/LexiqueList";
import styled from "@emotion/styled";

const LexiqueGlobal = styled.div`
  background-color: rgb(10, 20, 100);
`;

function lexique() {
  return (
    <div>
      <Head>
        <title>District Money - Lexique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <LexiqueGlobal>
        <LexiqueList />
      </LexiqueGlobal>
    </div>
  );
}

export default lexique;
