import Head from "next/head";
import React from "react";
import styled from "@emotion/styled";
import Question from "../components/Question";

const QuizzGlobal = styled.div`
  background-color: rgb(10, 20, 100);
`;

function quizz() {
  return (
    <QuizzGlobal>
      <Head>
        <title>District Money - Quizz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Question />
    </QuizzGlobal>
  );
}

export default quizz;
