import Head from "next/head";
import React from "react";
import Sectors from "../components/Sectors";
import styled from "@emotion/styled";

const SecteursGlobal = styled.div`
  background-color: rgb(10, 20, 100);
`;

function secteurs() {
  return (
    <SecteursGlobal>
      <Head>
        <title>District Money - Secteurs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Sectors />
    </SecteursGlobal>
  );
}

export default secteurs;
