import Head from "next/head";
import React from "react";
import SignIn from "../components/SignIn";
import styled from "@emotion/styled";

const SignInGlobal = styled.div`
  background-color: rgb(10, 20, 100);
`;

function signin() {
  return (
    <SignInGlobal>
      <Head>
        <title>District Money - Signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <SignIn />
    </SignInGlobal>
  );
}

export default signin;
