import Head from "next/head";
import React from "react";
import SignUp from "../components/Forms/SignUp";
import styled from "@emotion/styled";

const SignUpGlobal = styled.div`
  background-color: rgb(10, 20, 100);
`;

function signup() {
  return (
    <SignUpGlobal>
      <Head>
        <title>District Money - Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <SignUp />
    </SignUpGlobal>
  );
}

export default signup;
