import Head from "next/head";
import React from "react";

function bourse() {
  return (
    <div>
      <Head>
        <title>District Money - Bourse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      bourse
    </div>
  );
}

export default bourse;
