import Head from "next/head";
import React from "react";
import Simulation from "../components/Simulation";
import styled from "@emotion/styled";

const BourseGlobal = styled.div`
  background-color: rgb(10, 20, 100);
`;

function bourse() {
  return (
    <BourseGlobal>
      <Head>
        <title>District Money - Bourse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Simulation />
    </BourseGlobal>
  );
}

export default bourse;
