import Head from "next/head";
import styled from "@emotion/styled";
import Link from "next/link";

const HomeGlobal = styled.div`
  background-color: white;
`;

export default function Home() {
  return (
    <HomeGlobal>
      <Head>
        <title>District Money - Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Link href="/login" legacyBehavior>
        <a>Accès au formulaire</a>
      </Link>
    </HomeGlobal>
  );
}