import Head from "next/head";
import React from "react";

function lexique() {
  return (
    <div>
      <Head>
        <title>District Money - Lexique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      lexique
    </div>
  );
}

export default lexique;
