import Head from "next/head";
import React from "react";

function quizz() {
  return (
    <div>
      <Head>
        <title>District Money - Quizz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      quizz
    </div>
  );
}

export default quizz;
