import Head from "next/head";
import React from "react";

function secteurs() {
  return (
    <div>
      <Head>
        <title>District Money - Secteurs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      secteurs
    </div>
  );
}

export default secteurs;
